// import type { NavigationSection } from '@/components/shadcn-studio/blocks/menu-navigation'

import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Cal_Sans, Geist, JetBrains_Mono } from 'next/font/google'
import './globals.css'

const calSans = Cal_Sans({
  subsets: ['latin'],
  weight: '400',
  adjustFontFallback: false,
  variable: '--font-cal-sans',
})

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
})

// const navigationData: NavigationSection[] = [
//   {
//     title: 'About Us',
//     href: '#',
//   },
//   {
//     title: 'Testimonials',
//     href: '#',
//   },
//   {
//     title: 'Contact us',
//     href: '#',
//   },
//   {
//     title: 'Offers',
//     href: '#',
//   },
// ]

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'dark',
        'h-full',
        'antialiased',
        geistSans.variable,
        calSans.variable,
        jetBrainsMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        {/* <Header navigationData={navigationData} /> */}
        <main className="flex flex-1 flex-col pt-17.5">{children}</main>
      </body>
    </html>
  )
}
